//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaDeAulas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponible
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disponible()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int IdDisponible { get; set; }
        public int IdAula { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estado { get; set; }
    
        public virtual Aula Aula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
