//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaDeAulas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Reserva
    {
        [DisplayName("Codigo de Reserva")]
        public int IdReserva { get; set; }
        public int IdDisponible { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
    
        public virtual Disponible Disponible { get; set; }
    }
}
